services:
  srsenb_zmq:
    image: docker_srslte
    container_name: srsenb_zmq
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=enb_zmq
    expose:
      - "36412/sctp"
      - "2152/udp"
      - "2000/tcp"
      - "2001/tcp"
    networks:
      default:
        ipv4_address: ${SRS_ENB_IP}
    profiles:
      - ran-4g-srs
    labels:
      om.domain: "ran"
      om.nf: "enb"
      om.generation: "4g"
      om.project: "srslte"

  srsue_zmq:
    image: docker_srslte
    container_name: srsue_zmq
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ue_zmq
    expose:
      - "2000/tcp"
      - "2001/tcp"
    networks:
      default:
        ipv4_address: ${SRS_UE_IP}
    profiles:
      - ran-4g-srs
    labels:
      om.domain: "ran"
      om.nf: "ue"
      om.generation: "4g"
      om.project: "srslte"

  srsgnb_zmq:
    image: docker_srsran
    container_name: srsgnb_zmq
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ./srsran:/mnt/srsran
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=gnb_zmq
    expose:
      - "38412/sctp"
      - "2152/udp"
      - "2000/tcp"
      - "2001/tcp"
      - "8001/tcp"
    networks:
      default:
        ipv4_address: ${SRS_GNB_IP}
    profiles:
      - ran-5g-srs
    labels:
      om.domain: "ran"
      om.nf: "gnb"
      om.generation: "5g"
      om.project: "srsran"

  srsue_5g_zmq:
    image: docker_srslte
    container_name: srsue_5g_zmq
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ue_5g_zmq
    expose:
      - "2000/tcp"
      - "2001/tcp"
    networks:
      default:
        ipv4_address: ${SRS_UE_IP}
    profiles:
      - ran-5g-srs
    labels:
      om.domain: "ran"
      om.nf: "ue"
      om.generation: "5g"
      om.project: "srsran"

  nr_gnb:
    image: docker_ueransim
    container_name: nr_gnb
    stdin_open: true
    tty: true
    volumes:
      - ./ueransim:/mnt/ueransim
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ueransim-gnb
    expose:
      - "38412/sctp"
      - "2152/udp"
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      default:
        ipv4_address: ${NR_GNB_IP}
    profiles:
      - ran-5g-ueransim
    labels:
      om.domain: "ran"
      om.nf: "gnb"
      om.generation: "5g"
      om.project: "ueransim"

  nr_ue:
    image: docker_ueransim
    container_name: nr_ue
    stdin_open: true
    tty: true
    volumes:
      - ./ueransim:/mnt/ueransim
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ueransim-ue
    expose:
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      default:
        ipv4_address: ${NR_UE_IP}
    profiles:
      - ran-5g-ueransim
    labels:
      om.domain: "ran"
      om.nf: "ue"
      om.generation: "5g"
      om.project: "ueransim"

networks:
  default:
    name: docker_open5gs_default
    external: true
