# grafana/provisioning/datasources/prometheus.yml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ''
      exemplarTraceIdDestinations: []
    version: 1

  - name: Prometheus-OM-Module
    type: prometheus
    access: proxy
    url: http://om-module:9090
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableMetricsLookup: false
    version: 1
