apiVersion: 1

contactPoints:
  - orgId: 1
    name: Testbed Alerts
    receivers:
      - uid: email-receiver
        type: email
        settings:
          addresses: r.barrios@pucp.edu.pe
          subject: "[O&M Module] {{ .GroupLabels.alertname }}"
          message: |
            {{ range .Alerts }}
            Alert: {{ .Annotations.summary }}
            Description: {{ .Annotations.description }}
            Severity: {{ .Labels.severity }}
            State: {{ .Status }}
            Time: {{ .StartsAt }}
            {{ end }}
        disableResolveMessage: false
