apiVersion: 1

contactPoints:
  - orgId: 1
    name: 5G Lab Alerts
    receivers:
      - uid: email-receiver
        type: email
        settings:
          #addresses: ${ALERT_TO_EMAIL}
          addresses: rodrigoedu11@gmail.com
          subject: "[5G Testbed] {{ .GroupLabels.alertname }}"
          message: |
            {{ range .Alerts }}
            Alert: {{ .Annotations.summary }}
            Description: {{ .Annotations.description }}
            Severity: {{ .Labels.severity }}
            State: {{ .Status }}
            Time: {{ .StartsAt }}
            {{ end }}
        disableResolveMessage: false
