apiVersion: 1

policies:
  - orgId: 1
    receiver: Testbed Alerts
    group_by: [alertname, generation, severity]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    routes:
      - receiver: Testbed Alerts
        matchers:
          - generation = 5g
          - severity =~ "critical|warning"

      - receiver: Testbed Alerts
        matchers:
          - generation = 4g
          - severity =~ "critical|warning"
