apiVersion: 1

deleteRules:
#  - orgId: 1
#    uid: 4g-auth-failure
#  - orgId: 1
#    uid: 5g-auth-failure
#groups: []

groups:
  - orgId: 1
    name: 5G Core Alerts
    folder: 5G Testbed
    interval: 30s
    rules:
      - uid: 5g-reg-failure-rate
        title: "[5G] Tasa de fallos de registro > 20%"
        condition: C
        for: 1m
        noDataState: OK
        labels:
          severity: critical
          generation: 5g
        annotations:
          summary: "Tasa de fallos de registro 5G > 20%"
          description: >
            Más del 20% de los intentos de Initial Registratoin están fallando
            en los últimos 5 minutos. Revisar logs del AMF para identificar el tipo exacto.
            Solo dispara cuando hay al menos 3 intentos de registro en la ventana de evaluación.
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              expr: >
                sum(increase(fivegs_amffunction_rm_reginitfail[5m])) > 0
                and
                (
                  sum(increase(fivegs_amffunction_rm_reginitfail[5m]))
                  /
                  clamp_min(
                    sum(increase(fivegs_amffunction_rm_reginitfail[5m])) +
                    sum(increase(fivegs_amffunction_rm_reginitsucc[5m])),
                    1
                  )
                )
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: "__expr__"
            model:
              conditions:
                - evaluator:
                    params: [0.2]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              refId: C
              type: threshold
