{
 "title": "4G core",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory per nf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{domain=\"core\", generation=\"4g\"}) by (nf) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MME sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mme_session", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cpu per NF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_percent{domain=\"core\", generation=\"4g\"}) by (nf)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MME Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{nf=\"mme\"} |= ``"
    }
   ]
  },
  {
   "title": "UPF logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{nf=\"upf\"} |= ``"
    }
   ]
  },
  {
   "title": "Active eNBs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mme_enb_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SMF logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{nf=\"smf\"} |= ``"
    }
   ]
  },
  {
   "title": "Active UEs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ues_active", "legendFormat": "__auto" }
   ]
  }
 ]
}