global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'om-module-comprehensive'

rule_files:
  - 'rules/*.yml'

scrape_configs:
  # Official Network Function Endpoints
  - job_name: 'upf-official'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9094']
        labels:
          source: 'official_endpoint'
          component: 'upf'
          component_type: 'upf'
          nf_type: 'upf'
          deployment: '4G'
          component_ip: '172.22.0.8'

  - job_name: 'pcrf-official'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9096']
        labels:
          deployment: '4G'
          component_ip: '172.22.0.4'
          source: 'official_endpoint'
          component: 'pcrf'
          component_type: 'pcrf'
          nf_type: 'pcrf'

  - job_name: 'hss-official'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9097']
        labels:
          nf_type: 'mme'
          deployment: '4G'
          component_ip: '172.22.0.3'
          source: 'official_endpoint'
          component: 'hss'
          component_type: 'mme'

  - job_name: 'sgwc-official'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9099']
        labels:
          source: 'official_endpoint'
          component: 'sgwc'
          component_type: 'upf'
          nf_type: 'upf'
          deployment: '4G'
          component_ip: '172.22.0.5'

  - job_name: 'mme-official'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9095']
        labels:
          source: 'official_endpoint'
          component: 'mme'
          component_type: 'mme'
          nf_type: 'mme'
          deployment: '4G'
          component_ip: '172.22.0.9'

  - job_name: 'sgwu-official'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9098']
        labels:
          source: 'official_endpoint'
          component: 'sgwu'
          component_type: 'upf'
          nf_type: 'upf'
          deployment: '4G'
          component_ip: '172.22.0.6'

  - job_name: 'smf-official'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9092']
        labels:
          source: 'official_endpoint'
          component: 'smf'
          component_type: 'smf'
          nf_type: 'smf'
          deployment: '4G'
          component_ip: '172.22.0.7'

  # Container Resource Metrics
  - job_name: 'sgwu-container'
    scrape_interval: 10s
    metrics_path: '/container/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          source: 'container_stats'
          component: 'sgwu'
          component_type: '4G-User-Plane'
          deployment: '4G'
          container_id: 'sgwu'

  - job_name: 'webui-container'
    scrape_interval: 10s
    metrics_path: '/container/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          component_type: 'Web-Interface'
          deployment: '4G'
          container_id: 'webui'
          source: 'container_stats'
          component: 'webui'

  - job_name: 'mongo-container'
    scrape_interval: 10s
    metrics_path: '/container/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          source: 'container_stats'
          component: 'mongo'
          component_type: 'Database'
          deployment: '4G'
          container_id: 'mongo'

  - job_name: 'sgwc-container'
    scrape_interval: 10s
    metrics_path: '/container/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          component_type: '4G-Control-Plane'
          deployment: '4G'
          container_id: 'sgwc'
          source: 'container_stats'
          component: 'sgwc'

  - job_name: 'mme-container'
    scrape_interval: 10s
    metrics_path: '/container/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          source: 'container_stats'
          component: 'mme'
          component_type: '4G-Control-Plane'
          deployment: '4G'
          container_id: 'mme'

  - job_name: 'pcrf-container'
    scrape_interval: 10s
    metrics_path: '/container/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          container_id: 'pcrf'
          source: 'container_stats'
          component: 'pcrf'
          component_type: '4G-Policy'
          deployment: '4G'

  - job_name: 'hss-container'
    scrape_interval: 10s
    metrics_path: '/container/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          deployment: '4G'
          container_id: 'hss'
          source: 'container_stats'
          component: 'hss'
          component_type: '4G-Database'

  - job_name: 'upf-container'
    scrape_interval: 10s
    metrics_path: '/container/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          source: 'container_stats'
          component: 'upf'
          component_type: '5G-User-Plane'
          deployment: '4G'
          container_id: 'upf'

  - job_name: 'smf-container'
    scrape_interval: 10s
    metrics_path: '/container/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          component_type: '5G-Control-Plane'
          deployment: '4G'
          container_id: 'smf'
          source: 'container_stats'
          component: 'smf'

  # Component Health Checks
  - job_name: 'upf-health'
    scrape_interval: 15s
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          component_type: '5G-User-Plane'
          deployment: '4G'
          source: 'health_check'
          component: 'upf'

  - job_name: 'pcrf-health'
    scrape_interval: 15s
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          component: 'pcrf'
          component_type: '4G-Policy'
          deployment: '4G'
          source: 'health_check'

  - job_name: 'sgwc-health'
    scrape_interval: 15s
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          deployment: '4G'
          source: 'health_check'
          component: 'sgwc'
          component_type: '4G-Control-Plane'

  - job_name: 'mme-health'
    scrape_interval: 15s
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          source: 'health_check'
          component: 'mme'
          component_type: '4G-Control-Plane'
          deployment: '4G'

  - job_name: 'hss-health'
    scrape_interval: 15s
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          source: 'health_check'
          component: 'hss'
          component_type: '4G-Database'
          deployment: '4G'

  - job_name: 'smf-health'
    scrape_interval: 15s
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          component: 'smf'
          component_type: '5G-Control-Plane'
          deployment: '4G'
          source: 'health_check'

  - job_name: 'mongo-health'
    scrape_interval: 15s
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          source: 'health_check'
          component: 'mongo'
          component_type: 'Database'
          deployment: '4G'

  - job_name: 'sgwu-health'
    scrape_interval: 15s
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          source: 'health_check'
          component: 'sgwu'
          component_type: '4G-User-Plane'
          deployment: '4G'

  - job_name: 'webui-health'
    scrape_interval: 15s
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          component_type: 'Web-Interface'
          deployment: '4G'
          source: 'health_check'
          component: 'webui'

