[enb]
enb_id = 0x19E
mcc = MCC
mnc = MNC
mme_addr = MME_IP
gtp_bind_addr = SRS_ENB4_IP
s1c_bind_addr = SRS_ENB4_IP
s1c_bind_port = 0
n_prb = 50

[enb_files]
sib_config = /etc/srsran/sib.conf
rr_config  = /etc/srsran/rr.conf
rb_config = /etc/srsran/rb.conf

[rf]
tx_gain = 80
rx_gain = 40
device_name = zmq
device_args = fail_on_disconnect=true,tx_port=tcp://SRS_ENB4_IP:2006,rx_port=tcp://SRS_UE_BAD_APN_IP:2007,id=enb,base_srate=23.04e6

[gui]
enable = false

[scheduler]
nr_pdsch_mcs=28
