[rf]
freq_offset = 0
tx_gain = 80
device_name = zmq
device_args = tx_port=tcp://SRS_UE_BAD_IMSI_IP:2005,rx_port=tcp://SRS_ENB3_IP:2004,id=ue,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 3150

[usim]
mode = soft
algo = milenage
op  = 11111111111111111111111111111111
k    = 8baf473f2f8fd09487cccbd7097c6862
imsi = 001011234567901
imei = 353490069873322

[nas]
apn = internet
apn_protocol = ipv4

[gui]
enable = false
