[rf]
freq_offset = 0
tx_gain = 80
device_name = zmq
device_args = tx_port=tcp://SRS_UE_BAD_APN_IP:2009,rx_port=tcp://SRS_ENB2_IP:2002,id=ue,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 3150

[usim]
mode = soft
algo = milenage
op  = 11111111111111111111111111111111
k    = 8baf473f2f8fd09487cccbd7097c6862
imsi = 001011234567903
imei = 353490069873323

[nas]
apn = invalid_apn
apn_protocol = ipv4

[gui]
enable = false
