[rf]
freq_offset = 0
tx_gain = 80
device_name = zmq
device_args = tx_port=tcp://SRS_UE_BAD_KI_IP:2003,rx_port=tcp://SRS_ENB2_IP:2002,id=ue,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 3150

[usim]
mode = soft
algo = milenage
op  = 11111111111111111111111111111111
k    = FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
imsi = 001011234567902
imei = 353490069873321

[nas]
apn = internet
apn_protocol = ipv4

[gui]
enable = false
